from email.mime import image
from multiprocessing.sharedctypes import Value
from tkinter import*
import random
import tkinter.font as tkFont


#NDVE=NOM DE VOTRE ENFANT
#NDF=NOM DE FAMILLE
#NLPC=NOM LES PLUS CONNUS
#NF=LISTE NOM DE FILLE
#NG=LISTE NOM DE GARCON


my_font="{Roboto Condensed} 14"


BOY_NAME=['Adrien',
			'Aimé',
			'Alain',
			'Alexandre',
			'Alfred',
			'Alphonse',
			'André',
			'Antoine',
			'Arthur',
			'Auguste',
			'Augustin',
			'Benjamin',
			'Benoît',
			'Bernard',
			'Bertrand',
			'Charles',
			'Christophe',
			'Daniel',
			'David',
			'Denis',
			'Édouard',
			'Émile',
			'Emmanuel',
			'Éric',
			'Étienne',
			'Eugène',
			'François',
			'Franck',
			'Frédéric',
			'Gabriel',
			'Georges',
			'Gérard',
			'Gilbert',
			'Gilles',
			'Grégoire',
			'Guillaume',
			'Guy',
			'William',
			'Henri',
			'Honoré',
			'Hugues',
			'Isaac',
			'Jacques',
			'Jean',
			'Jérôme',
			'Joseph',
			'Jules',
			'Julien',
			'Laurent',
			'Léon',
			'Louis',
			'Luc',
			'Lucas',
			'Marc',
			'Marcel',
			'Martin',
			'Matthieu',
			'Maurice',
			'Michel',
			'Nicolas',
			'Noël',
			'Olivier',
			'Patrick',
			'Paul',
			'Philippe',
			'Pierre',
			'Raymond',
			'Rémy',
			'René',
			'Richard',
			'Robert',
			'Roger',
			'Roland',
			'Sébastien',
			'Stéphane',
			'Théodore',
			'Théophile',
			'Thibaut',
			'Thibault',
			'Thierry',
			'Thomas',
			'Timothée',
			'Tristan',
			'Victor',
			'Vincent',
			'Xavier',
			'Yves',
			'Zacharie',
			'Adélaïde',
			'Adèle',
			'Adrienne',
			'Agathe',
			'Agnès',
			'Aimée',
			'Alexandrie',
			'Alix',
			'Alexandria',
			'Alex',
			'Alice',
			'Amélie',
			'Anaïs',
			'Anastasie',
			'Andrée',
			'Anne',
			'Anouk',
			'Antoinette',
			'Arnaude',
			'Astrid',
			'Audrey',
			'Aurélie',
			'Aurore',
			'Bernadette',
			'Brigitte',
			'Capucine',
			'Caroline',
			'Catherine',
			'Cécile',
			'Céline',
			'Célina',
			'Chantal',
			'Charlotte',
			'Christelle',
			'Christiane',
			'Christine',
			'Claire',
			'Claudine',
			'Clémence',
			'Colette',
			'Constance',
			'Corinne',
			'Danielle',
			'Denise',
			'Diane',
			'Dorothée',
			'Édith',
			'Éléonore',
			'Élisabeth',
			'Élise',
			'Élodie',
			'Émilie',
			'Emmanuelle',
			'Françoise',
			'Frédérique',
			'Gabrielle',
			'Geneviève',
			'Hélène',
			'Henriette',
			'Hortense',
			'Inès',
			'Isabelle',
			'Jacqueline',
			'Jeanne',
			'Jeannine',
			'Joséphine',
			'Josette',
			'Julie',
			'Juliette',
			'Laetitia',
			'Laure',
			'Laurence',
			'Lorraine',
			'Louise',
			'Luce',
			'Lucie',
			'Lucy',
			'Madeleine',
			'Manon',
			'Marcelle',
			'Margaux',
			'Margaud',
			'Margot',
			'Marguerite',
			'Margot',
			'Margaret',
			'Maggie',
			'daisy',
			'Marianne',
			'Marie',
			'Marine',
			'Marthe',
			'Martine',
			'Maryse',
			'Mathilde',
			'Michèle',
			'Michelle',
			'Michelle',
			'Monique',
			'Nathalie',
			'Nath',
			'Nathalie',
			'Nicole',
			'Noémi',
			'Océane',
			'Odette',
			'Olivie',
			'Patricia',
			'Paulette',
			'Pauline',
			'Pénélope',
			'Philippine',
			'Renée',
			'Sabine',
			'Simone',
			'Sophie',
			'Stéphanie',
			'Susanne',
			'Suzanne',
			'Susan',
			'Suzanne',
			'Sylvie',
			'Thérèse',
			'Valentine',
			'Valérie',
			'Véronique',
			'Victoire',
			'Virginie',
			'Zoé',
			'Camille',
			'Claude',
			'Dominique'
            'Adrien',
			'Aimé',
			'Alain',
			'Alexandre',
			'Alfred',
			'Alphonse',
			'André',
			'Antoine',
			'Arthur',
			'Auguste',
			'Augustin',
			'Benjamin',
			'Benoît',
			'Bernard',
			'Bertrand',
			'Charles',
			'Christophe',
			'Daniel',
			'David',
			'Denis',
			'Édouard',
			'Émile',
			'Emmanuel',
			'Éric',
			'Étienne',
			'Eugène',
			'François',
			'Franck',
			'Frédéric',
			'Gabriel',
			'Georges',
			'Gérard',
			'Gilbert',
			'Gilles',
			'Grégoire',
			'Guillaume',
			'Guy',
			'William',
			'Henri',
			'Honoré',
			'Hugues',
			'Isaac',
			'Jacques',
			'Jean',
			'Jérôme',
			'Joseph',
			'Jules',
			'Julien',
			'Laurent',
			'Léon',
			'Louis',
			'Luc',
			'Lucas',
			'Marc',
			'Marcel',
			'Martin',
			'Matthieu',
			'Maurice',
			'Michel',
			'Nicolas',
			'Noël',
			'Olivier',
			'Patrick',
			'Paul',
			'Philippe',
			'Pierre',
			'Raymond',
			'Rémy',
			'René',
			'Richard',
			'Robert',
			'Roger',
			'Roland',
			'Sébastien',
			'Stéphane',
			'Théodore',
			'Théophile',
			'Thibaut',
			'Thibault',
			'Thierry',
			'Thomas',
			'Timothée',
			'Tristan',
			'Victor',
			'Vincent',
			'Xavier',
			'Yves',
			'Zacharie',
			'Adélaïde',
			'Adèle',
			'Adrienne',
			'Agathe',
			'Agnès',
			'Aimée',
			'Alexandrie',
			'Alix',
			'Alexandria',
			'Alex',
			'Alice',
			'Amélie',
			'Anaïs',
			'Anastasie',
			'Andrée',
			'Anne',
			'Anouk',
			'Antoinette',
			'Arnaude',
			'Astrid',
			'Audrey',
			'Aurélie',
			'Aurore',
			'Bernadette',
			'Brigitte',
			'Capucine',
			'Caroline',
			'Catherine',
			'Cécile',
			'Céline',
			'Célina',
			'Chantal',
			'Charlotte',
			'Christelle',
			'Christiane',
			'Christine',
			'Claire',
			'Claudine',
			'Clémence',
			'Colette',
			'Constance',
			'Corinne',
			'Danielle',
			'Denise',
			'Diane',
			'Dorothée',
			'Édith',
			'Éléonore',
			'Élisabeth',
			'Élise',
			'Élodie',
			'Émilie',
			'Emmanuelle',
			'Françoise',
			'Frédérique',
			'Gabrielle',
			'Geneviève',
			'Hélène',
			'Henriette',
			'Hortense',
			'Inès',
			'Isabelle',
			'Jacqueline',
			'Jeanne',
			'Jeannine',
			'Joséphine',
			'Josette',
			'Julie',
			'Juliette',
			'Laetitia',
			'Laure',
			'Laurence',
			'Lorraine',
			'Louise',
			'Luce',
			'Lucie',
			'Lucy',
			'Madeleine',
			'Manon',
			'Marcelle',
			'Margaux',
			'Margaud',
			'Margot',
			'Marguerite',
			'Margot',
			'Margaret',
			'Maggie',
			'daisy',
			'Marianne',
			'Marie',
			'Marine',
			'Marthe',
			'Martine',
			'Maryse',
			'Mathilde',
			'Michèle',
			'Michelle',
			'Michelle',
			'Monique',
			'Nathalie',
			'Nath',
			'Nathalie',
			'Nicole',
			'Noémi',
			'Océane',
			'Odette',
			'Olivie',
			'Patricia',
			'Paulette',
			'Pauline',
			'Pénélope',
			'Philippine',
			'Renée',
			'Sabine',
			'Simone',
			'Sophie',
			'Stéphanie',
			'Susanne',
			'Suzanne',
			'Susan',
			'Suzanne',
			'Sylvie',
			'Thérèse',
			'Valentine',
			'Valérie',
			'Véronique',
			'Victoire',
			'Virginie',
			'Zoé',
			'Camille',
			'Claude',
			'Dominique']

NG=random.choice(BOY_NAME)


def resetButton():
    entryNDF.delete(0, END)
    entryNDVE.delete(0,END)


def recommancer_choix():
        entryNDVE.delete(0,END)

def action():
    N = entryNDF.get()
    N2= entryNDF.get(),random.choice(BOY_NAME)
    entryNDVE.insert(0,N2)



babyname= Tk()


babyname.geometry("960x540")


can = Canvas(babyname,width=960,height=540)
img = PhotoImage(file="transparent.png")
can.create_image(-100,-390,image=img,anchor=NW )
can.place(x=0,y=0)



NDF = Label(babyname, text="Entrez votre nom de famille:",font=my_font)
NDF.place(x=300,y=299)
entryNDF=Entry(babyname)
entryNDF.place(x=515,y=299)

NDVE = Label(babyname, text="Nom future enfant : ",font=my_font)
NDVE.place(x=300,y=350)
entryNDVE=Entry(babyname)
entryNDVE.place(x=515,y=350)



    


Valider=Button(babyname,text="Valider le nom de famille ",command=action,font=my_font)
Valider.pack
Valider.place(x=10,y=500)

second_champ_clean=Button(babyname,text="Effacer second champ",command=recommancer_choix,font=my_font)
second_champ_clean.pack()
second_champ_clean.place(x=212,y=500)

resetButton = Button(babyname,text="Réinitialiser la page",command=resetButton,font=my_font)
resetButton.pack()
resetButton.place(x=590,y=500)

quitter= Button(babyname,text="Quitter l'application ",command=babyname.quit,font=my_font)
quitter.pack()
quitter.place(x=750,y=500)

babyname.mainloop()

